# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 3
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/JFM/Desktop/Jeen_Nekkit6-master/miriscv_testsoc/miriscv_testsoc.cache/wt [current_project]
set_property parent.project_path C:/Users/JFM/Desktop/Jeen_Nekkit6-master/miriscv_testsoc/miriscv_testsoc.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/JFM/Desktop/Jeen_Nekkit6-master/miriscv_testsoc/miriscv_testsoc.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem {
  C:/Users/JFM/Desktop/Jeen_Nekkit6-master/sw/testsoc_text.dat
  C:/Users/JFM/Desktop/Jeen_Nekkit6-master/sw/testsoc_data.dat
}
read_verilog -library xil_defaultlib -sv {
  C:/Users/JFM/Desktop/Jeen_Nekkit6-master/testsoc/apb_timer/apb_timer.sv
  C:/Users/JFM/Desktop/Jeen_Nekkit6-master/rtl/include/miriscv_pkg.sv
  C:/Users/JFM/Desktop/Jeen_Nekkit6-master/rtl/include/miriscv_alu_pkg.sv
  C:/Users/JFM/Desktop/Jeen_Nekkit6-master/rtl/miriscv_alu.sv
  C:/Users/JFM/Desktop/Jeen_Nekkit6-master/rtl/include/miriscv_gpr_pkg.sv
  C:/Users/JFM/Desktop/Jeen_Nekkit6-master/rtl/miriscv_core.sv
  C:/Users/JFM/Desktop/Jeen_Nekkit6-master/rtl/include/miriscv_decode_pkg.sv
  C:/Users/JFM/Desktop/Jeen_Nekkit6-master/rtl/include/miriscv_opcodes_pkg.sv
  C:/Users/JFM/Desktop/Jeen_Nekkit6-master/rtl/miriscv_decode_stage.sv
  C:/Users/JFM/Desktop/Jeen_Nekkit6-master/rtl/include/miriscv_mdu_pkg.sv
  C:/Users/JFM/Desktop/Jeen_Nekkit6-master/rtl/miriscv_decoder.sv
  C:/Users/JFM/Desktop/Jeen_Nekkit6-master/rtl/miriscv_div.sv
  C:/Users/JFM/Desktop/Jeen_Nekkit6-master/rtl/miriscv_fetch_stage.sv
  C:/Users/JFM/Desktop/Jeen_Nekkit6-master/rtl/miriscv_fetch_unit.sv
  C:/Users/JFM/Desktop/Jeen_Nekkit6-master/rtl/miriscv_gpr.sv
  C:/Users/JFM/Desktop/Jeen_Nekkit6-master/rtl/include/miriscv_lsu_pkg.sv
  C:/Users/JFM/Desktop/Jeen_Nekkit6-master/rtl/miriscv_lsu.sv
  C:/Users/JFM/Desktop/Jeen_Nekkit6-master/rtl/miriscv_mdu.sv
  C:/Users/JFM/Desktop/Jeen_Nekkit6-master/testsoc/miriscv_ram.sv
  C:/Users/JFM/Desktop/Jeen_Nekkit6-master/rtl/miriscv_rvfi_controller.sv
  C:/Users/JFM/Desktop/Jeen_Nekkit6-master/rtl/miriscv_signextend.sv
  C:/Users/JFM/Desktop/Jeen_Nekkit6-master/testsoc/apb_timer/timer.sv
  C:/Users/JFM/Desktop/Jeen_Nekkit6-master/testsoc/miriscv_test_soc.sv
}
read_vhdl -library xil_defaultlib {
  C:/Users/JFM/Desktop/Jeen_Nekkit6-master/testsoc/apb_uart/apb_uart.vhd
  C:/Users/JFM/Desktop/Jeen_Nekkit6-master/testsoc/apb_uart/slib_clock_div.vhd
  C:/Users/JFM/Desktop/Jeen_Nekkit6-master/testsoc/apb_uart/slib_counter.vhd
  C:/Users/JFM/Desktop/Jeen_Nekkit6-master/testsoc/apb_uart/slib_edge_detect.vhd
  C:/Users/JFM/Desktop/Jeen_Nekkit6-master/testsoc/apb_uart/slib_fifo.vhd
  C:/Users/JFM/Desktop/Jeen_Nekkit6-master/testsoc/apb_uart/slib_input_filter.vhd
  C:/Users/JFM/Desktop/Jeen_Nekkit6-master/testsoc/apb_uart/slib_input_sync.vhd
  C:/Users/JFM/Desktop/Jeen_Nekkit6-master/testsoc/apb_uart/slib_mv_filter.vhd
  C:/Users/JFM/Desktop/Jeen_Nekkit6-master/testsoc/apb_uart/uart_baudgen.vhd
  C:/Users/JFM/Desktop/Jeen_Nekkit6-master/testsoc/apb_uart/uart_interrupt.vhd
  C:/Users/JFM/Desktop/Jeen_Nekkit6-master/testsoc/apb_uart/uart_receiver.vhd
  C:/Users/JFM/Desktop/Jeen_Nekkit6-master/testsoc/apb_uart/uart_transmitter.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/JFM/Desktop/Jeen_Nekkit6-master/xdc/miriscv_test_soc.xdc
set_property used_in_implementation false [get_files C:/Users/JFM/Desktop/Jeen_Nekkit6-master/xdc/miriscv_test_soc.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top miriscv_test_soc -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef miriscv_test_soc.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file miriscv_test_soc_utilization_synth.rpt -pb miriscv_test_soc_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
